set(CMAKE_SYSTEM_NAME iOS)

if(NOT DEFINED PULSE_IOS_PLATFORM)
    set(PULSE_IOS_PLATFORM "SIMULATOR64")
endif()

if(PULSE_IOS_PLATFORM STREQUAL "OS64")
    set(CMAKE_OSX_SYSROOT "iphoneos")
    set(CMAKE_OSX_ARCHITECTURES "arm64")
elseif(PULSE_IOS_PLATFORM STREQUAL "SIMULATORARM64")
    set(CMAKE_OSX_SYSROOT "iphonesimulator")
    set(CMAKE_OSX_ARCHITECTURES "arm64")
else()
    set(CMAKE_OSX_SYSROOT "iphonesimulator")
    set(CMAKE_OSX_ARCHITECTURES "x86_64")
endif()

if(NOT DEFINED CMAKE_OSX_DEPLOYMENT_TARGET)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "15.0")
endif()

set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE "NO")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
